-- Base de datos: `minerabd`
CREATE DATABASE IF NOT EXISTS `minerabd`;
USE `minerabd`;

-- --------------------------------------------------------

CREATE TABLE `tbformulario` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) DEFAULT NULL,
  `edad` int(11) DEFAULT NULL,
  `area` varchar(255) DEFAULT NULL,
  `puesto_actual` varchar(255) DEFAULT NULL,
  `anios_puesto` int(11) DEFAULT NULL,
  `puesto_postula` varchar(255) DEFAULT NULL,
  `motivo_postula` varchar(255) DEFAULT NULL,
  `fecha_postula` date DEFAULT NULL,
  `estado` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;

INSERT INTO `tbformulario` (`id`, `nombre`, `edad`, `area`, `puesto_actual`, `anios_puesto`, `puesto_postula`, `motivo_postula`, `fecha_postula`, `estado`) VALUES
(1, 'Jonatan Alvarez Fuentes', 32, 'DS-SISTEMAS', 'ANALISTA TÉCNICO', 2, 'ANALISTA TÉCNICO SENIOR', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(2, 'Micaela Coello Cubas', 42, 'DS-SISTEMAS', 'ANALISTA DE CALIDAD', 2, 'ANALISTA DE CALIDAD SENIOR', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(3, 'Anita Correa Navas', 34, 'DS-SISTEMAS', 'PROGRAMADOR SENIOR', 3, 'ARQUITECTO DE SOLUCIONES', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(4, 'Arcelia España Bolaños', 38, 'DS-SISTEMAS', 'ANALISTA TÉCNICO', 3, 'LIDER TÉCNICO', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(5, 'Fulgencio Benito-Cortina', 29, 'DS-SISTEMAS', 'ANALISTA JUNIOR', 3, 'ANALISTA DE SISTEMAS', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(6, 'Felipa Luís Duque', 31, 'DS-SISTEMAS', 'ANALISTA FUNCIONAL', 3, 'ANALISTA FUNCINAL SENIOR', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(7, 'Anselma Alberdi Ibáñez', 36, 'DS-SISTEMAS', 'ARQUITECTO DE SOLUCIONES', 3, 'JEFE DE PROYECTOS', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(8, 'Saturnina Lobo Benavides', 38, 'DS-SISTEMAS', 'ANALISTA DE BASE DE DATOS', 3, 'ANALISTA DBA SENIOR', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(9, 'Basilio Sosimo Rosales Barceló', 35, 'DS-SISTEMAS', 'ANALISTA DE CALIDAD', 3, 'ANALISTA DE CALIDAD SENIOR', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(10, 'Plinio Sáez Sevilla', 34, 'DS-SISTEMAS', 'COORDINADOR DE PROYECTOS', 3, 'JEFE DE PROYECTOS', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(11, 'Tamara Mateos Ramón', 33, 'DS-SISTEMAS', 'ANALISTA DE CALIDAD', 3, 'ANALISTA DE CALIDAD SENIOR', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(12, 'Adalberto del Robledo', 32, 'DS-SISTEMAS', 'ANALISTA TÉCNICO', 3, 'ANALISTA TÉCNICO SENIOR', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(13, 'Gastón Egea Figuerola', 30, 'DS-SISTEMAS', 'PROGRAMADOR SENIOR', 3, 'ARQUITECTO DE SOLUCIONES', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(14, 'Felicidad Barceló Bárcena', 29, 'DS-SISTEMAS', 'ASISTENTE DE SISTEMAS', 1, 'ANALISTA JUNIOR', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(15, 'Bernarda Escudero Rovira', 28, 'DS-SISTEMAS', 'ANALISTA TECNICO SENIOR', 3, 'AUDITOR DE SISTEMAS', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(16, 'Ciríaco Tomé Cortes', 35, 'DS-SISTEMAS', 'ESPECIALISTA EN SOPORTE NIVEL 3', 3, 'ARQUITECTO DE INFRAESTRUCTURA', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(17, 'René Cáceres bernal', 45, 'DS-SISTEMAS', 'ANALISTA DE CALIDAD', 3, 'ANALISTA DE CALIDAD SENIOR', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(18, 'Nacho Augusto Pons Valbuena', 37, 'DS-SISTEMAS', 'ANALISTA TÉCNICO', 3, 'ANALISTA TÉCNICO SENIOR', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(19, 'Azahara Mosquera Ródenas', 39, 'DS-SISTEMAS', 'ASISTENTE DE SISTEMAS', 1, 'PROGRAMADOR JUNIOR', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE'),
(20, 'Clotilde Gomez Posada', 29, 'DS-SISTEMAS', 'PROGRAMADOR SENIOR', 3, 'ARQUITECTO DE SOLUCIONES', 'CRECIMIENTO PROFESIONAL', '2021-12-04', 'PENDIENTE');

-- --------------------------------------------------------